-- Migration 121: Task Proto-Plan
-- Purpose: Store proto-plan payloads for downstream workers
-- This table captures proto-plans generated by the coordinator for cognitive/planner routes,
-- allowing downstream workers to retrieve and execute the plans.
--
-- Dependencies: 001 (tasks table)
-- Architecture:
-- - Foreign key to tasks(id) for task association
-- - Unique constraint on task_id (one proto-plan per task)
-- - JSONB column for flexible proto-plan storage
-- - Indexes for efficient querying by task_id

BEGIN;

-- Ensure required extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================================
-- Create task_proto_plan table
-- ============================================================================

CREATE TABLE IF NOT EXISTS task_proto_plan (
    id BIGSERIAL PRIMARY KEY,
    task_id UUID NOT NULL UNIQUE REFERENCES tasks(id) ON DELETE CASCADE,
    route TEXT NOT NULL DEFAULT 'unknown',  -- Route decision (fast, planner, cognitive, hgnn)
    proto_plan JSONB NOT NULL DEFAULT '{}'::jsonb,  -- Proto-plan payload for downstream workers
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_task_proto_plan_task_id 
    ON task_proto_plan (task_id);

CREATE INDEX IF NOT EXISTS idx_task_proto_plan_route 
    ON task_proto_plan (route);

CREATE INDEX IF NOT EXISTS idx_task_proto_plan_created_at 
    ON task_proto_plan (created_at DESC);

-- GIN index for JSONB queries on proto_plan
CREATE INDEX IF NOT EXISTS idx_task_proto_plan_proto_plan 
    ON task_proto_plan USING GIN (proto_plan);

-- ============================================================================
-- Trigger to update updated_at timestamp
-- ============================================================================

CREATE OR REPLACE FUNCTION update_task_proto_plan_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_task_proto_plan_updated_at
    BEFORE UPDATE ON task_proto_plan
    FOR EACH ROW
    EXECUTE FUNCTION update_task_proto_plan_updated_at();

-- ============================================================================
-- Comments for documentation
-- ============================================================================

COMMENT ON TABLE task_proto_plan IS 
    'Proto-plan payloads for downstream workers. Stores proto-plans generated by the coordinator for cognitive/planner routes.';

COMMENT ON COLUMN task_proto_plan.task_id IS 
    'Foreign key to tasks table. Unique constraint ensures one proto-plan per task.';

COMMENT ON COLUMN task_proto_plan.route IS 
    'Route decision that generated this proto-plan: fast, planner, cognitive, hgnn, etc.';

COMMENT ON COLUMN task_proto_plan.proto_plan IS 
    'Proto-plan payload (JSONB) containing execution plan details for downstream workers. May be truncated if exceeding MAX_PROTO_PLAN_BYTES.';

COMMENT ON COLUMN task_proto_plan.created_at IS 
    'Timestamp when the proto-plan was first created.';

COMMENT ON COLUMN task_proto_plan.updated_at IS 
    'Timestamp when the proto-plan was last updated (via upsert).';

COMMENT ON INDEX idx_task_proto_plan_task_id IS 
    'Index for fast lookups of proto-plans by task_id.';

COMMENT ON INDEX idx_task_proto_plan_route IS 
    'Index for analyzing proto-plans by route type.';

COMMENT ON INDEX idx_task_proto_plan_proto_plan IS 
    'GIN index for efficient JSONB queries on proto-plan fields.';

-- ============================================================================
-- Verification
-- ============================================================================

DO $$
DECLARE
    table_exists BOOLEAN;
    index_count INT;
BEGIN
    -- Check if table exists
    SELECT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' 
        AND table_name = 'task_proto_plan'
    ) INTO table_exists;

    -- Count indexes
    SELECT COUNT(*) INTO index_count
    FROM pg_indexes
    WHERE schemaname = 'public'
    AND tablename = 'task_proto_plan';

    RAISE NOTICE '';
    RAISE NOTICE '📋 Task Proto-Plan Migration Summary:';
    RAISE NOTICE '   • Table created: %', CASE WHEN table_exists THEN '✅' ELSE '❌' END;
    RAISE NOTICE '   • Indexes created: %', index_count;
    RAISE NOTICE '   • Purpose: Store proto-plan payloads for downstream workers';
    RAISE NOTICE '';
END;
$$;

COMMIT;
