# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import robot_sim_pb2 as robot__sim__pb2


class RobotSimStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/robotsim.RobotSim/GetState',
                request_serializer=robot__sim__pb2.Empty.SerializeToString,
                response_deserializer=robot__sim__pb2.RobotState.FromString,
                )
        self.Goto = channel.unary_unary(
                '/robotsim.RobotSim/Goto',
                request_serializer=robot__sim__pb2.MotionCommand.SerializeToString,
                response_deserializer=robot__sim__pb2.Ack.FromString,
                )


class RobotSimServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Goto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotSimServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=robot__sim__pb2.Empty.FromString,
                    response_serializer=robot__sim__pb2.RobotState.SerializeToString,
            ),
            'Goto': grpc.unary_unary_rpc_method_handler(
                    servicer.Goto,
                    request_deserializer=robot__sim__pb2.MotionCommand.FromString,
                    response_serializer=robot__sim__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robotsim.RobotSim', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RobotSim(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robotsim.RobotSim/GetState',
            robot__sim__pb2.Empty.SerializeToString,
            robot__sim__pb2.RobotState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Goto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robotsim.RobotSim/Goto',
            robot__sim__pb2.MotionCommand.SerializeToString,
            robot__sim__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
