# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_sim.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frobot_sim.proto\x12\x08robotsim\"\x07\n\x05\x45mpty\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x8b\x01\n\nRobotState\x12,\n\x04head\x18\x01 \x03(\x0b\x32\x1e.robotsim.RobotState.HeadEntry\x12\x10\n\x08\x61ntennas\x18\x02 \x03(\x02\x12\x10\n\x08\x62ody_yaw\x18\x03 \x01(\x02\x1a+\n\tHeadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\xa3\x01\n\rMotionCommand\x12/\n\x04head\x18\x01 \x03(\x0b\x32!.robotsim.MotionCommand.HeadEntry\x12\x10\n\x08\x61ntennas\x18\x02 \x03(\x02\x12\x10\n\x08\x62ody_yaw\x18\x03 \x01(\x02\x12\x10\n\x08\x64uration\x18\x04 \x01(\x02\x1a+\n\tHeadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32m\n\x08RobotSim\x12\x31\n\x08GetState\x12\x0f.robotsim.Empty\x1a\x14.robotsim.RobotState\x12.\n\x04Goto\x12\x17.robotsim.MotionCommand\x1a\r.robotsim.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_sim_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROBOTSTATE_HEADENTRY']._options = None
  _globals['_ROBOTSTATE_HEADENTRY']._serialized_options = b'8\001'
  _globals['_MOTIONCOMMAND_HEADENTRY']._options = None
  _globals['_MOTIONCOMMAND_HEADENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=29
  _globals['_EMPTY']._serialized_end=36
  _globals['_ACK']._serialized_start=38
  _globals['_ACK']._serialized_end=55
  _globals['_ROBOTSTATE']._serialized_start=58
  _globals['_ROBOTSTATE']._serialized_end=197
  _globals['_ROBOTSTATE_HEADENTRY']._serialized_start=154
  _globals['_ROBOTSTATE_HEADENTRY']._serialized_end=197
  _globals['_MOTIONCOMMAND']._serialized_start=200
  _globals['_MOTIONCOMMAND']._serialized_end=363
  _globals['_MOTIONCOMMAND_HEADENTRY']._serialized_start=154
  _globals['_MOTIONCOMMAND_HEADENTRY']._serialized_end=197
  _globals['_ROBOTSIM']._serialized_start=365
  _globals['_ROBOTSIM']._serialized_end=474
# @@protoc_insertion_point(module_scope)
