namespace: seedcore-dev
nameSuffix: -dev
# Note: commonLabels is deprecated but still functional in Kustomize v5.7.1
# TODO: Migrate to modern labels syntax when Kustomize provides better migration tools
commonLabels: { stage: dev }
commonAnnotations: { seedcore.io/stage: dev }

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: seedcore-client-env
    literals:
      - RAY_ADDRESS=ray://seedcore-svc-head-svc:10001
      - RAY_NAMESPACE=seedcore-dev
      - RAY_SERVE_ADDRESS=http://seedcore-svc-head-svc:8000
      - RAY_DASHBOARD_ADDRESS=http://seedcore-svc-head-svc:8265

resources:
  - ../../base

images:
  - name: yourrepo/seedcore-api
    newName: seedcore-app
    newTag: latest
  - name: yourrepo/seedcore-serve
    newName: seedcore-serve
    newTag: latest

patches:
  - target: { kind: Deployment, name: seedcore-serve }
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: SEEDCORE_OPTIONAL_BACKENDS, value: "true" }
  - target: { kind: Deployment, name: seedcore-api }
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: SEEDCORE_OPTIONAL_BACKENDS, value: "true" }


