namespace: seedcore-dev
nameSuffix: -dev
# Note: commonLabels is deprecated but still functional in Kustomize v5.7.1
# TODO: Migrate to modern labels syntax when Kustomize provides better migration tools
commonLabels: { stage: dev }
commonAnnotations: { seedcore.io/stage: dev }

resources:
  - ../../base

images:
  - name: yourrepo/seedcore-api
    newName: seedcore-app
    newTag: latest
  - name: yourrepo/seedcore-serve
    newName: seedcore-serve
    newTag: latest

patches:
  - target: { kind: Deployment, name: seedcore-serve }
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: ray://seedcore-dev-head-svc:10001
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: SEEDCORE_OPTIONAL_BACKENDS, value: "true" }
  - target: { kind: Deployment, name: seedcore-api }
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: ray://seedcore-dev-head-svc:10001
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: SEEDCORE_OPTIONAL_BACKENDS, value: "true" }


