# SeedCore default configuration
seedcore:
  telemetry_port: 8088
  grpc_port: 50055
  organs:
    - cognitive
    - actuator
    - utility
  entropy_floor: 0.2
  weights:
    w_pair: 1.0
    w_hyper: 1.0
    alpha: 0.5
    lambda_reg: 0.01
    beta_mem: 0.2
  
  # COA Organism Configuration
  organism:
    organ_types:
      # - id: "cognitive_organ_1"
      #   type: "Cognitive"
      #   description: "Handles reasoning, planning, and complex task decomposition."
      #   agent_count: 0
      - id: "actuator_organ_1"
        type: "Actuator"
        description: "Executes actions and interacts with external APIs."
        agent_count: 1
        task_types: ["execute", "workflow_step", "side_effect"]
      - id: "utility_organ_1"
        type: "Utility"
        description: "Manages memory, health checks, and internal system tasks."
        agent_count: 1
        task_types: ["general_query", "health_check", "status", "ping"] 