apiVersion: batch/v1
kind: Job
metadata:
  name: seedcore-db-init
  namespace: seedcore-dev
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-init
          image: python:3.12-slim
          env:
            - name: PYTHONPATH
              value: /app
          command:
            - /bin/sh
            - -lc
            - |
              set -euo pipefail
              apt-get update
              # If you only use Postgres, libpq-dev is enough. For MySQL C client, include default-libmysqlclient-dev.
              apt-get install -y --no-install-recommends build-essential libpq-dev
              rm -rf /var/lib/apt/lists/*
              python -m pip install --upgrade pip
              if [ -f /app/requirements.txt ]; then
                pip install -r /app/requirements.txt
              else
                # Postgres + MySQL (pure-Python) drivers; drop one if you don't need it
                pip install "SQLAlchemy>=2.0" psycopg2-binary PyMySQL
              fi
              python /app/scripts/init_database.py
          envFrom:
            - secretRef:
                name: seedcore-env-secret
                optional: true
          volumeMounts:
            - name: project-source
              mountPath: /app
      volumes:
        - name: project-source
          hostPath:
            path: /project
            type: Directory
