apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seedcore-data-pvc
  namespace: seedcore-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
