#!/usr/bin/env python3
"""Unit tests for Neo4jGraph helper behavior."""

from seedcore.memory.backends.neo4j_graph import _sanitize_rel


def test_sanitize_rel_preserves_valid_underscore_labels():
    assert _sanitize_rel("GENERATED_BY") == "GENERATED_BY"


def test_sanitize_rel_normalizes_common_inputs():
    assert _sanitize_rel("generated by") == "GENERATED_BY"
    assert _sanitize_rel("related-to") == "RELATED_TO"


def test_sanitize_rel_rejects_non_alpha_prefix():
    assert _sanitize_rel("123_REL") == "RELATED_TO"
