#!/usr/bin/env bash
# Shared localhost-friendly environment for experimental SeedCore host mode.

set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd -P)"

export PROJECT_ROOT
export PYTHONPATH="${PROJECT_ROOT}/src"
export PATH="${PROJECT_ROOT}/.venv/bin:/opt/homebrew/opt/postgresql@17/bin:${PATH}"
export SEEDCORE_APP_ROOT="${SEEDCORE_APP_ROOT:-${PROJECT_ROOT}}"
export SEEDCORE_CONFIG_DIR="${SEEDCORE_CONFIG_DIR:-${PROJECT_ROOT}/config}"
export SEEDCORE_DATA_DIR="${SEEDCORE_DATA_DIR:-${PROJECT_ROOT}/data}"
export SEEDCORE_OPT_DIR="${SEEDCORE_OPT_DIR:-${PROJECT_ROOT}/opt}"

export POSTGRES_HOST="${POSTGRES_HOST:-127.0.0.1}"
export POSTGRES_PORT="${POSTGRES_PORT:-5432}"
export POSTGRES_DB="${POSTGRES_DB:-seedcore}"
export POSTGRES_USER="${POSTGRES_USER:-ningli}"
export PG_DSN="${PG_DSN:-postgresql://${POSTGRES_USER}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}}"
export PG_DSN_ASYNC="${PG_DSN_ASYNC:-postgresql+asyncpg://${POSTGRES_USER}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}}"
export SEEDCORE_PG_DSN="${SEEDCORE_PG_DSN:-${PG_DSN}}"

export REDIS_HOST="${REDIS_HOST:-127.0.0.1}"
export REDIS_PORT="${REDIS_PORT:-6379}"
export REDIS_DB="${REDIS_DB:-0}"
export REDIS_URL="${REDIS_URL:-redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}}"

export RAY_HOST="${RAY_HOST:-127.0.0.1}"
export RAY_GCS_PORT="${RAY_GCS_PORT:-26079}"
export RAY_CLIENT_PORT="${RAY_CLIENT_PORT:-23001}"
export RAY_DASHBOARD_PORT="${RAY_DASHBOARD_PORT:-8265}"
export RAY_ADDRESS="${RAY_ADDRESS:-${RAY_HOST}:${RAY_GCS_PORT}}"
export RAY_CLIENT_ADDRESS="${RAY_CLIENT_ADDRESS:-ray://${RAY_HOST}:${RAY_CLIENT_PORT}}"
export RAY_STATUS_ADDRESS="${RAY_STATUS_ADDRESS:-${RAY_HOST}:${RAY_GCS_PORT}}"
export RAY_NAMESPACE="${RAY_NAMESPACE:-seedcore-local}"
export SEEDCORE_NS="${SEEDCORE_NS:-${RAY_NAMESPACE}}"
export SERVE_GATEWAY="${SERVE_GATEWAY:-http://${RAY_HOST}:8000}"

export SEEDCORE_API_URL="${SEEDCORE_API_URL:-http://127.0.0.1:8002}"
export HAL_BASE_URL="${HAL_BASE_URL:-http://127.0.0.1:8003}"
export COG_BASE_URL="${COG_BASE_URL:-${SERVE_GATEWAY}/cognitive}"
export ORG_BASE_PATH="${ORG_BASE_PATH:-/organism}"
export COG_BASE_PATH="${COG_BASE_PATH:-/cognitive}"
export SERVE_BASE_PATH="${SERVE_BASE_PATH:-/ml}"

export POSTGRES_POOL_SIZE="${POSTGRES_POOL_SIZE:-5}"
export POSTGRES_MAX_OVERFLOW="${POSTGRES_MAX_OVERFLOW:-5}"

export ENABLE_ML_SERVICE="${ENABLE_ML_SERVICE:-false}"
export DGL_GRAPHBOLT_SKIP="${DGL_GRAPHBOLT_SKIP:-1}"
export RAY_USAGE_STATS_ENABLED="${RAY_USAGE_STATS_ENABLED:-0}"
export SEEDCORE_SKIP_EAGER_RAY="${SEEDCORE_SKIP_EAGER_RAY:-1}"
