# This file is auto-generated by create_seedcore_skeleton.py
"""
Organ registry + lookup table used by the router (fast vs escalate).
"""

from typing import Dict
from .base import Organ

class OrganRegistry:
    def __init__(self):
        self._organs: Dict[str, Organ] = {}

    def add(self, organ: Organ):
        self._organs[organ.organ_id] = organ

    def get(self, organ_id: str) -> Organ:
        return self._organs[organ_id]

    def all(self) -> list[Organ]:
        return list(self._organs.values())
