# This file is auto-generated by create_seedcore_skeleton.py
"""
Lifecycle transitions (Scout <-> Employed <-> Specialist).
Threshold logic from §2.1; event emitters feed Energy updates.
"""

from .base import Agent

PROMOTE_TAU_C = 0.7
PROMOTE_TAU_U = 0.5

def evaluate_lifecycle(agent: Agent):
    if agent.capability >= PROMOTE_TAU_C and agent.mem_util >= PROMOTE_TAU_U:
        # promote to Employed/Specialist
        pass
