# version: "3.9"  # Deprecated in Docker Compose V2, kept for legacy tooling

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: seedcore-postgres
    profiles: ["core"]
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup/init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql:ro
    networks:
      - seedcore-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    container_name: seedcore-mysql
    profiles: ["core"]
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: seedcore
      MYSQL_USER: seedcore
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./setup/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql:ro
    networks:
      - seedcore-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:5.15
    container_name: seedcore-neo4j
    profiles: ["core"]
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - seedcore-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7474/browser/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Redis service removed - Ray uses its own internal Redis on port 6379

  db-seed:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: seedcore-db-seed:latest
    container_name: seedcore-db-seed
    profiles: ["core", "seed"]
    environment:
      PYTHONPATH: /app:/app/src
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    networks:
      - seedcore-network
    volumes:
      - ..:/app
      - ./artifacts:/data
    command: python -m scripts.populate_mlt_simple
    restart: "no"

  ray-head:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ray
      # dockerfile: docker/Dockerfile.ray.optimized
    image: seedcore-ray-head:latest
    container_name: seedcore-ray-head
    profiles: ["ray"]
    shm_size: '4gb'
    working_dir: /app
    environment:
      PYTHONPATH: /app:/app/src
      # ── stream every worker's stdout/stderr to the container log ──
      RAY_worker_stdout_file: /dev/stdout
      RAY_worker_stderr_file: /dev/stderr
      # ── keep the driver  (seedcore‑api)  log lines too ──
      RAY_log_to_driver: 1
      # ── lower Ray's own log level so we still see our INFO lines ──
      RAY_BACKEND_LOG_LEVEL: info
      # ── disable usage stats collection (silences warning) ──
      RAY_USAGE_STATS_ENABLED: "0"
      # ── disable additional metrics server to prevent port conflicts ──
      RAY_DISABLE_METRICS_SERVER: "1"
      # ── Ray 2.20.0 specific configurations ──
      RAY_METRICS_EXPORT_PORT: "8080"
      RAY_DASHBOARD_METRICS_PORT: "8080"
      # ── Ray Dashboard monitoring configuration ──
      RAY_PROMETHEUS_HOST: http://prometheus:9090
      RAY_GRAFANA_HOST: http://grafana:3000
      RAY_GRAFANA_IFRAME_HOST: ${PUBLIC_GRAFANA_URL}
      RAY_PROMETHEUS_NAME: Prometheus
      # ── Ray Serve configuration for dashboard integration ──
      RAY_SERVE_ENABLE_DASHBOARD_INTEGRATION: "1"
      RAY_SERVE_DASHBOARD_HOST: "0.0.0.0"
      RAY_SERVE_DASHBOARD_PORT: "8000"
      # ── Asyncio configuration to prevent Ray Serve controller errors ──
      PYTHONASYNCIODEBUG: "1"
      RAY_SERVE_ASYNC_DEBUG: "1"
      # ── Ray Serve stability settings ──
      RAY_SERVE_CONTROLLER_HEARTBEAT_TIMEOUT_S: "30"
      RAY_SERVE_PROXY_HEARTBEAT_TIMEOUT_S: "30"

    volumes:
      - ..:/app  # Mounts the project root into /app in the container
      - ./artifacts:/data  # Mount artifacts directory for UUID access
    ports:
      - "8265:8265"      # dashboard UI
      - "8266:8266"      # dashboard UI (fallback)
      - "52365:52365"    # agent gRPC port
      - "52366:52366"    # agent HTTP port
      - "10001:10001"    # Ray head gRPC / jobs / client
      - "6379:6379"      # Ray internal Redis
      - "8080:8080"      # Ray metrics export port
      - "8000:8000"      # Ray Serve application port
    networks:
      - seedcore-network
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/health || ray health-check"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 90s # Generous grace period for startup
    command: ["/bin/bash", "docker/start-ray-with-serve.sh"]

  # Ray workers are defined in ray-workers.yml
  # To start workers: docker compose -f ray-workers.yml up -d

  seedcore-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: seedcore-api:latest
    container_name: seedcore-api
    profiles: ["api"]
    working_dir: /app
    environment:
      PYTHONPATH: /app:/app/src
      RAY_ADDRESS: ray://ray-head:10001
      RAY_memory_usage_threshold: 0.8
      RAY_memory_monitor_refresh_ms: 2500
    env_file:
      - .env
    ports:
      - "80:8002"
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      ray-head:
        condition: service_started
    networks:
      - seedcore-network
    volumes:
      - ..:/app  # Mounts the project root into /app in the container
      - ./artifacts:/data  # Mount artifacts directory for UUID access
    deploy:
      resources:
        limits:
          memory: 4g
    command:
      - /bin/sh
      - -c
      - |
        if [ "$DEV_RELOAD" = "1" ]; then
          uvicorn src.seedcore.telemetry.server:app --host 0.0.0.0 --port 8002 --reload
        else
          uvicorn src.seedcore.telemetry.server:app --host 0.0.0.0 --port 8002
        fi

  # ───────────────────────────────────────────────────────────────────── #
  # Observability stack
  # ───────────────────────────────────────────────────────────────────── #
  
  # Nginx proxy for Ray metrics with CORS support
  ray-metrics-proxy:
    image: nginx:alpine
    container_name: seedcore-ray-metrics-proxy
    profiles: ["obs"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:8081"
    depends_on:
      - ray-head
    networks:
      - seedcore-network

  # Dashboard proxy to intercept localhost:8082 requests
  ray-dashboard-proxy:
    image: nginx:alpine
    container_name: seedcore-ray-dashboard-proxy
    profiles: ["obs"]
    volumes:
      - ./dashboard-proxy.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8082:8080"
    depends_on:
      - ray-head
      - ray-metrics-proxy
    networks:
      - seedcore-network

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: seedcore-prometheus
    profiles: ["obs"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus_rules.yml:/etc/prometheus/prometheus_rules.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    depends_on:
      - seedcore-api
      - ray-head
    networks:
      - seedcore-network

  grafana:
    image: grafana/grafana:11.0.0
    container_name: seedcore-grafana
    profiles: ["obs"]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=seedcore
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - seedcore-network

  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: seedcore-node-exporter
    profiles: ["obs"]
    ports:
      - "9100:9100"
    networks:
      - seedcore-network

volumes:
  postgres_data:
  mysql_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  seedcore-network:
    external: true

