version: "3.8"

services:
  ray-serve:
    image: rayproject/ray:latest
    command: bash -lc "ray start --address='ray-head:6379' --block"
    environment:
      RAY_ADDRESS: ray-head:6379
      SEEDCORE_NS: ${SEEDCORE_NS:-seedcore-prod}
      SEEDCORE_STAGE: ${SEEDCORE_STAGE:-prod}
      OPENAI_API_KEY: ${OPENAI_API_KEY:?}
    depends_on:
      - ray-head
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8g


