apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xgb-pvc
  namespace: seedcore-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

