# This file is auto-generated by create_seedcore_skeleton.py
"""
Energy API surface.
Expose a Python call read_energy() and a server-facing handler to serve /energy/gradient
(JSON payload defined in §3.x.6 and §8 metrics schema).
"""

from .ledger import EnergyLedger
from typing import Dict, Any
import time

_ledger = EnergyLedger()

def read_energy() -> Dict[str, float]:
    return {
        "pair": _ledger.pair,
        "hyper": _ledger.hyper,
        "entropy": _ledger.entropy,
        "reg": _ledger.reg,
        "mem": _ledger.mem,
        "total": _ledger.total,
    }

def energy_gradient_payload(extra: Dict[str, Any] | None = None) -> Dict[str, Any]:
    payload = {
        "ts": int(time.time()),
        "E_terms": read_energy(),
        # placeholders
        "agent_grad_proxy": {},
        "mem_pressure": {},
    }
    if extra:
        payload.update(extra)
    return payload
