# Copyright 2024 SeedCore Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is auto-generated by create_seedcore_skeleton.py
"""
Energy API surface.
Expose a Python call read_energy() and a server-facing handler to serve /energy/gradient
(JSON payload defined in §3.x.6 and §8 metrics schema).
"""

from .ledger import EnergyLedger
from typing import Dict, Any
import time

_ledger = EnergyLedger()

def read_energy() -> Dict[str, float]:
    return {
        "pair": _ledger.pair,
        "hyper": _ledger.hyper,
        "entropy": _ledger.entropy,
        "reg": _ledger.reg,
        "mem": _ledger.mem,
        "total": _ledger.total,
    }

def energy_gradient_payload(extra: Dict[str, Any] | None = None) -> Dict[str, Any]:
    payload = {
        "ts": int(time.time()),
        "E_terms": read_energy(),
        # placeholders
        "agent_grad_proxy": {},
        "mem_pressure": {},
    }
    if extra:
        payload.update(extra)
    return payload
