# Copyright 2024 SeedCore Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is auto-generated by create_seedcore_skeleton.py
"""
CostVQ estimator: proxy cost for compression vs fidelity trade (Section 7, 3.x.4).
"""

def cost_vq(bytes_used: int, recon_loss: float, stale_s: float,
            w_b=1.0, w_r=1.0, w_s=0.5) -> float:
    return w_b*bytes_used + w_r*recon_loss + w_s*stale_s
