# This file is auto-generated by create_seedcore_skeleton.py
"""
CostVQ estimator: proxy cost for compression vs fidelity trade (Section 7, 3.x.4).
"""

def cost_vq(bytes_used: int, recon_loss: float, stale_s: float,
            w_b=1.0, w_r=1.0, w_s=0.5) -> float:
    return w_b*bytes_used + w_r*recon_loss + w_s*stale_s
