# Copyright 2024 SeedCore Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is auto-generated by create_seedcore_skeleton.py
"""
Memory tiers Ma/Mw/Mlt/Mfb (Section 7).
Simple in-memory placeholders; integrate storage backends later.
"""

class MemoryTier:
    def __init__(self, name: str):
        self.name = name
        self.store = {}

    def write(self, k, v):
        self.store[k] = v

    def read(self, k):
        return self.store.get(k)

Ma = MemoryTier('Ma')
Mw = MemoryTier('Mw')
Mlt = MemoryTier('Mlt')
Mfb = MemoryTier('Mfb')
