# This file is auto-generated by create_seedcore_skeleton.py
"""
Memory tiers Ma/Mw/Mlt/Mfb (Section 7).
Simple in-memory placeholders; integrate storage backends later.
"""

class MemoryTier:
    def __init__(self, name: str):
        self.name = name
        self.store = {}

    def write(self, k, v):
        self.store[k] = v

    def read(self, k):
        return self.store.get(k)

Ma = MemoryTier('Ma')
Mw = MemoryTier('Mw')
Mlt = MemoryTier('Mlt')
Mfb = MemoryTier('Mfb')
