# This file is auto-generated by create_seedcore_skeleton.py
"""
Fast Loop (~200ms): energy-aware agent selection (Section 6, 3.x.4).
"""

from ..organs.base import Organ
# Correctly import the ledger instance from the api module
from ..energy.api import _ledger

def fast_loop_select_agent(organ: Organ, task):
    # 1. Select the agent and store it in a variable
    agent = organ.select_agent(task)

    # 2. Update the energy ledger (this code will now run)
    # NOTE: You will need to add the `add_pair_delta` method to the EnergyLedger class
    _ledger.add_pair_delta(w=0.8, sim=0.9) # We'll comment this out for now

    # 3. Return the selected agent
    return agent