# Copyright 2024 SeedCore Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is auto-generated by create_seedcore_skeleton.py
"""
Fast Loop (~200ms): energy-aware agent selection (Section 6, 3.x.4).
"""

from ..organs.base import Organ
# Correctly import the ledger instance from the api module
from ..energy.api import _ledger

def fast_loop_select_agent(organ: Organ, task):
    # 1. Select the agent and store it in a variable
    agent = organ.select_agent(task)

    # 2. Update the energy ledger (this code will now run)
    # NOTE: You will need to add the `add_pair_delta` method to the EnergyLedger class
    _ledger.add_pair_delta(w=0.8, sim=0.9) # We'll comment this out for now

    # 3. Return the selected agent
    return agent