# seedcore/dispatcher/persistence/interfaces.py

from typing import Protocol, List, Dict, Any

class TaskRepositoryProtocol(Protocol):
    async def claim_batch(self, batch_size: int, exclusions: List[str]) -> List[Dict[str, Any]]: ...
    async def complete(self, task_id: str, result_json: str) -> None: ...
    async def retry(self, task_id: str, error: str, delay_s: int) -> None: ...
    async def fail(self, task_id: str, error: str) -> None: ...
    async def renew_lease(self, task_id: str) -> None: ...
    async def requeue_stuck(self, timeout_s: int) -> int: ...
    async def enforce_snapshot_id_for_batch(self, task_ids: List[str]) -> int: ...