services:
  seedcore-serve:
    build:
      context: ..
      dockerfile: docker/Dockerfile.serve
    image: seedcore-serve:latest
    container_name: seedcore-serve
    working_dir: /app
    environment:
      PYTHONPATH: /app:/app/src
      RAY_ADDRESS: ray://ray-head:10001
      RAY_NAMESPACE: seedcore
      SERVE_HTTP_HOST: 0.0.0.0
      SERVE_HTTP_PORT: 8000
      COG_APP_NAME: seedcore-dev-cognitive_core
      SEEDCORE_NS: seedcore
      SEEDCORE_STAGE: dev
      # Database connections (these will need to be updated for your environment)
      PG_DSN: postgresql://postgres:password@postgres:5432/postgres
      MYSQL_DATABASE_URL: mysql+mysqlconnector://seedcore:password@mysql:3306/seedcore
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
    ports:
      - "8001:8000"  # Map to different port to avoid conflict with ray-head
    volumes:
      - ..:/app  # Mounts the project root into /app in the container
      - ./artifacts:/data  # Mount artifacts directory for UUID access
    deploy:
      resources:
        limits:
          memory: 1g
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=5).read()"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped


