services:
  sc_cognitive-serve:
    build:
      context: ..
      dockerfile: docker/Dockerfile.cognitive-serve
    image: sc_cognitive-serve:latest
    container_name: sc_cognitive-serve
    profiles: ["cognitive-serve"]
    working_dir: /app
    environment:
      PYTHONPATH: /app:/app/src
      RAY_ADDRESS: ray://ray-head:10001
      RAY_NAMESPACE: seedcore
      SERVE_HTTP_HOST: 0.0.0.0
      SERVE_HTTP_PORT: 8000
      SEEDCORE_NS: seedcore
      SEEDCORE_STAGE: dev
      # Database connections (if needed for cognitive core)
      PG_DSN: postgresql://postgres:password@postgresql-pgbouncer:6432/postgres
      MYSQL_DATABASE_URL: mysql+mysqlconnector://seedcore:password@mysql:3306/seedcore
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
    env_file:
      - .env
    ports:
      - "8002:8000"  # Map to port 8002 to avoid conflicts
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      redis:
        condition: service_healthy
      ray-head:
        condition: service_healthy
    networks:
      - seedcore-network
    volumes:
      - ..:/app  # Mounts the project root into /app in the container
      - ./artifacts:/data  # Mount artifacts directory for UUID access
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '2.0'
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=5).read()"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped

networks:
  seedcore-network:
    external: true
