{{- if .Values.pgbouncer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql.fullname" . }}-pgbouncer
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pgbouncer
  template:
    metadata:
      labels:
        {{- include "postgresql.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: pgbouncer
    spec:
      containers:
      - name: pgbouncer
        image: "{{ .Values.pgbouncer.image.repository }}:{{ .Values.pgbouncer.image.tag }}"
        ports:
        - name: pgbouncer
          containerPort: 6432
          protocol: TCP
        env:
        - name: POSTGRESQL_HOST
          value: {{ include "postgresql.fullname" . }}
        - name: POSTGRESQL_PORT_NUMBER
          value: "5432"
        - name: POSTGRESQL_USERNAME
          value: {{ .Values.pgbouncer.auth.username }}
        - name: POSTGRESQL_PASSWORD
          value: {{ .Values.pgbouncer.auth.password }}
        - name: POSTGRESQL_DATABASE
          value: {{ .Values.postgresql.auth.database }}
        - name: PGBOUNCER_PORT
          value: "6432"
        - name: PGBOUNCER_DATABASE
          value: {{ .Values.postgresql.auth.database }}
        - name: PGBOUNCER_USERNAME
          value: {{ .Values.pgbouncer.auth.username }}
        - name: PGBOUNCER_PASSWORD
          value: {{ .Values.pgbouncer.auth.password }}
        resources:
          {{- toYaml .Values.pgbouncer.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: pgbouncer
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: pgbouncer
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}-pgbouncer
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgbouncer
spec:
  type: {{ .Values.pgbouncer.service.type }}
  ports:
    - port: {{ .Values.pgbouncer.service.port }}
      targetPort: pgbouncer
      protocol: TCP
      name: pgbouncer
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pgbouncer
{{- end }}


