name: Run Tests

on:
  push:
    branches: [ "main", "release/1.0.0" ]
  pull_request:
    branches: [ "main", "release/1.0.0" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] || pip install -e .
          pip install pytest

      - name: Run pytest
        run: pytest tests -q --disable-warnings --maxfail=1

